spring.application.name=aweb.com

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sistema_vendas}
spring.datasource.username=${DB_USER:usuario}
spring.datasource.password=${DB_PASSWORD:senha123}

server.port=${SERVER_PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true